name: pull_request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - ".gitignore"

jobs:
  package:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu2004
          - centos7
    container:
      image: vesoft/nebula-dev:${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16.4

      - name: build
        run: |
          make
          mv nebula-dump nebula-dump-${{ matrix.os }}
