name: pull_request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - ".gitignore"

  

jobs:
  package:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu2004
          - centos7
    container:
      image: vesoft/nebula-dev:${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16.4

      - name: prepare
        run: |
          case ${{ matrix.os }} in
          ubuntu2004)
            apt-get update 
            apt-get install -y \
              libsnappy-dev \
              zlib1g-dev \
              libbz2-dev \
              liblz4-dev \
              libzstd-dev
            ;;
          centos7)
            yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
            yum install snappy-devel lz4-devel libzstd-devel -y
            ;;
          esac
      - name: build
        run: |
          make
          mv nebula-dump nebula-dump-${{ matrix.os }}
