name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  package:
    name: package and upload release assets
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu:20.04
          - centos:7
    container:
      image: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16.4

      - name: prepare
        id: prepare
        run: |
          case ${{ matrix.os }} in
          ubuntu:20.04)
            apt-get update 
            apt-get install -y \
              git \
              make \
              gcc \
              g++ \
              libsnappy-dev \
              zlib1g-dev \
              libbz2-dev \
              liblz4-dev \
              libzstd-dev
            echo "::set-output name=p::ubuntu2004"
            ;;
          centos:7)
            yum install -y epel-release 
            yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
            yum install -y --nogpgcheck\
                wget \
                libzstd libzstd-devel \
                snappy snappy-devel \
                zlib zlib-devel \
                bzip2 bzip2-devel \
                lz4-devel \
                make \
                gcc \
                which \
                gcc-c++ \
                python3 \
                perl \
                git 
            echo "::set-output name=p::centos7"
            ;;
          esac

      - name: build
        run: |
          make
          mv nebula-dump nebula-dump-${{ steps.prepare.outputs.p }}

      - name: upload release asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            nebula-dump-${{ steps.prepare.outputs.p }}
